### ISSUE TITLE
Kawkab with Fira Code?

### ISSUE THREAD

**Issue by simurgh9** [aiaf/kawkab-mono#5]
I am not sure how difficult this might be, I tried doing this myself but got incorrect or just off results. Can you please make a version of Kawkab with Fira Code and all of it's ligatures instead of Source Code Pro?

**Comment by aiaf** [comment]
Hi @simurgh9, sorry but I currently have no plans for this. You could try again and see if you get anywhere or report any specific problems that need addressing.

**Comment by ghazyami** [comment]
@simurgh9 you can check this out https://github.com/aster-phoenix/hybrid-mono-fonts
